# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170624_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('business_name',)},
        ),
    ]
