# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170715_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address_invoice', models.BooleanField()),
                ('address_shipping', models.BooleanField()),
                ('company_name', models.CharField(max_length=100)),
                ('vat', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address_invoice', models.BooleanField()),
                ('address_shipping', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='relation',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='contact_city',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='contact_country',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='contact_postcode',
        ),
        migrations.AddField(
            model_name='relationaddress',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Relation'),
        ),
    ]
