# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20170720_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownaddress',
            name='address_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownaddress',
            name='address_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownaddress',
            name='vat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relationaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relationaddress',
            name='address_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relationaddress',
            name='address_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
