# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20170720_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='is_client',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='is_supplier',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
