# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20170802_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
