# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20170831_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='address_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='address_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(choices=[(b'AT', b'Austria'), (b'BE', b'Belgium'), (b'DK', b'Denmark'), (b'FR', b'France'), (b'DE', b'Germany'), (b'GB', b'Great Brittain'), (b'IT', b'Italy'), (b'NL', b'Netherlands'), (b'NO', b'Norway'), (b'RU', b'Russia'), (b'SE', b'Sweden'), (b'CH', b'Switzerland')], default='BE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='postcode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='address1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='address_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relation',
            name='address_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relation',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='country',
            field=models.CharField(choices=[(b'AT', b'Austria'), (b'BE', b'Belgium'), (b'DK', b'Denmark'), (b'FR', b'France'), (b'DE', b'Germany'), (b'GB', b'Great Brittain'), (b'IT', b'Italy'), (b'NL', b'Netherlands'), (b'NO', b'Norway'), (b'RU', b'Russia'), (b'SE', b'Sweden'), (b'CH', b'Switzerland')], default='BE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='postcode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownaddress',
            name='country',
            field=models.CharField(choices=[(b'AT', b'Austria'), (b'BE', b'Belgium'), (b'DK', b'Denmark'), (b'FR', b'France'), (b'DE', b'Germany'), (b'GB', b'Great Brittain'), (b'IT', b'Italy'), (b'NL', b'Netherlands'), (b'NO', b'Norway'), (b'RU', b'Russia'), (b'SE', b'Sweden'), (b'CH', b'Switzerland')], max_length=100),
        ),
        migrations.AlterField(
            model_name='relationaddress',
            name='country',
            field=models.CharField(choices=[(b'AT', b'Austria'), (b'BE', b'Belgium'), (b'DK', b'Denmark'), (b'FR', b'France'), (b'DE', b'Germany'), (b'GB', b'Great Brittain'), (b'IT', b'Italy'), (b'NL', b'Netherlands'), (b'NO', b'Norway'), (b'RU', b'Russia'), (b'SE', b'Sweden'), (b'CH', b'Switzerland')], max_length=100),
        ),
    ]
