# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20170907_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='address_invoice',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='address_shipping',
        ),
        migrations.RemoveField(
            model_name='ownaddress',
            name='address_invoice',
        ),
        migrations.RemoveField(
            model_name='ownaddress',
            name='address_shipping',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='address_invoice',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='address_shipping',
        ),
    ]
