# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_auto_20170910_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
