# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20170911_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='payment_days',
            field=models.IntegerField(default=0, verbose_name='Days to pay invoice'),
        ),
    ]
