# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_relation_payment_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='vat_regime',
            field=models.CharField(choices=[('NONE', 'No Vat'), ('ECZROUTPUT', 'Zero Rated EC Goods Income'), ('OUTPUT2', 'Default')], default='OUTPUT2', max_length=20),
        ),
    ]
