# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_relation_vat_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='vat_regime',
            field=models.CharField(choices=[('NONE', 'Non-EU'), ('ECZROUTPUT', 'With EU VAT-number'), ('OUTPUT2', 'Default')], default='OUTPUT2', max_length=20),
        ),
    ]
