# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_auto_20170911_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownaddress',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationaddress',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
