# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_auto_20170912_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownaddress',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationaddress',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
