# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_auto_20171004_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentComission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Agent')),
            ],
            options={
                'ordering': ('from_amount',),
            },
        ),
    ]
