# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_agentcomission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentcomission',
            options={'ordering': ('-from_amount',)},
        ),
    ]
