# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_auto_20171011_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentComission',
            new_name='AgentCommission',
        ),
        migrations.AlterModelOptions(
            name='agentcommission',
            options={'ordering': ('from_amount',)},
        ),
    ]
