# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_auto_20171011_1043'),
        ('contacts', '0027_auto_20171006_0453'),
    ]

    operations = [
    ]
