# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_agent_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='currency',
            field=models.CharField(choices=[(b'EUR', b'EUR'), (b'USD', b'USD'), (b'GBP', b'GBP')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='relation',
            name='customer_type',
            field=models.CharField(choices=[(b'DROP', b'Drop-Shipping'), (b'CLAS', b'Classic')], default='CLAS', max_length=4),
        ),
    ]
