# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0001_initial'),
        ('contacts', '0032_auto_20171127_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricelists.PriceList'),
        ),
    ]
