# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0033_relation_price_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='price_list',
            new_name='custom_price_list',
        ),
    ]
