# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0113_auto_20171203_1521'),
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrp', models.FloatField(blank=True, null=True)),
                ('per_1', models.FloatField(blank=True, null=True)),
                ('per_6', models.FloatField(blank=True, null=True)),
                ('per_12', models.FloatField(blank=True, null=True)),
                ('per_48', models.FloatField(blank=True, null=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelists.PriceList')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
    ]
