# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0002_pricelistitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricelistitem',
            table='sales_pricelistitem',
        ),
        migrations.AlterModelTable(
            name='pricetransport',
            table='sales_pricetransport',
        ),
    ]
