# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0004_auto_20171209_0833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricelist',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='pricelistitem',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='pricetransport',
            table='sales',
        ),
    ]
