# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0064_auto_20170727_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20)),
                ('production_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockLocation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProductionOrder')),
            ],
        ),
    ]
