# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20170728_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
