# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20170728_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('WC', 'Waiting for confirmation'), ('WA', 'Waiting delivery'), ('DL', 'Delivered'), ('IN', 'Invoice added')], default='DR', max_length=2),
        ),
    ]
