# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_auto_20170912_1741'),
        ('inventory', '0087_auto_20170917_1625'),
        ('production', '0005_productionorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='est_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='invoice_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.OwnAddress'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_to', to='inventory.StockLocation'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='production_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_location', to='inventory.StockLocation'),
        ),
    ]
