# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20170918_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='_marked_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
