# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20171005_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderdelivery',
            name='_sprintpack_pre_advice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
