# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionorderdelivery__sprintpack_pre_advice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorderdelivery',
            options={'verbose_name_plural': 'ProductionOrderDeliveries'},
        ),
    ]
