# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20171005_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorderdelivery',
            options={'verbose_name_plural': 'Production order deliveries'},
        ),
    ]
