# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20171006_0337'),
        ('production', '0007_productionorder__marked_for_delivery'),
    ]

    operations = [
    ]
