# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20171024_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
