# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0056_auto_20170715_0629'),
        ('contacts', '0005_auto_20170720_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ivoice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.OwnAddress')),
                ('ship_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockLocation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Relation')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Material')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseOrder')),
            ],
        ),
    ]
