# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20170720_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='added_to_temp_stock',
            field=models.BooleanField(default=False),
        ),
    ]
