# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseorderitem_added_to_temp_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderConfirmationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_attachment', models.FileField(upload_to='media/purchase/confirmation/%Y/%m/%d')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseOrder')),
            ],
        ),
    ]
