# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseorderconfirmationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='_qty_delivered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='fully_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
