# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20170720_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='_qty_delivered',
            field=models.IntegerField(default=0),
        ),
    ]
