# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20170720_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='qty',
            field=models.FloatField(),
        ),
    ]
