# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20170720_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='_qty_delivered',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='qty',
            field=models.FloatField(),
        ),
    ]
