# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20170720_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('WC', 'Waiting for confirmation'), ('WA', 'Waiting delivery'), ('DL', 'Delivered'), ('IN', 'Invoice added')], default='DR', max_length=2),
        ),
    ]
