# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaseorder_supplier_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='ivoice_to',
            new_name='invoice_to',
        ),
    ]
