# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_auto_20170720_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='est_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
