# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchaseorder_est_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'delieveries'},
        ),
    ]
