# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_delivery_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='transport_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
