# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_auto_20170920_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'deliveries'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='_awaiting_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
