# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_auto_20171024_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('WC', 'Waiting for confirmation'), ('WA', 'Awaiting delivery'), ('PL', 'Partially Delivered'), ('DL', 'Delivered'), ('IN', 'Invoice added'), ('CA', 'Cancelled')], default='DR', max_length=2),
        ),
    ]
