# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('custom_label_logo', models.ImageField(blank=True, null=True, upload_to='media/logos/label_logo/%Y/%m/%d')),
            ],
        ),
    ]
