# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_billofmaterials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
    ]
