# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_materials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillOfMaterials',
            new_name='BillOfMaterial',
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='quanity_needed',
            new_name='quantity_needed',
        ),
    ]
