# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170401_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_per_usage_unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='unit_usage',
            field=models.CharField(choices=[('T', 'Time'), ('M', 'Meters')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
