# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170401_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit_usage',
            field=models.CharField(choices=[('H', 'Hours'), ('M', 'Meters')], max_length=1),
        ),
    ]
