# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170401_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='unit_purchase',
            field=models.CharField(choices=[('MO', 'Months'), ('PC', 'Pieces'), ('PL', 'Pieces'), ('ME', 'Meters'), ('RO', 'Rolls')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='unit_usage_in_purchase',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_usage',
            field=models.CharField(choices=[('HU', 'Hours'), ('PI', 'Pieces'), ('ME', 'Meters')], max_length=2),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier'),
            preserve_default=False,
        ),
    ]
