# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20170428_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='number',
            field=models.IntegerField(),
        ),
    ]
