# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170428_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_vector', models.FileField(upload_to='patterns/vector/%Y/%m/%d')),
                ('pattern_image', models.FileField(upload_to='patterns/image/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_size', models.CharField(max_length=3)),
                ('full_size', models.CharField(max_length=20)),
                ('measurements', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='GR', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ean_code',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='products/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='inventory.Size'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together=set([('number', 'size')]),
        ),
    ]
