# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20170621_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='measurements',
        ),
    ]
