# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_size_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='products/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='product_model_images/%Y/%m/%d')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
    ]
