# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20170621_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='media/products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productmodelimage',
            name='image',
            field=models.FileField(upload_to='media/product_model_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productpattern',
            name='pattern_image',
            field=models.FileField(upload_to='media/patterns/image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productpattern',
            name='pattern_vector',
            field=models.FileField(upload_to='media/patterns/vector/%Y/%m/%d'),
        ),
    ]
