# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20170622_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Colour'),
        ),
    ]
