# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20170622_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
