# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20170622_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean_code',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
