# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20170622_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit_purchase',
            field=models.CharField(choices=[('MO', 'Months'), ('PC', 'Pieces'), ('ME', 'Meters'), ('RO', 'Rolls'), ('BA', 'Bags')], max_length=2, verbose_name='Purchase unit'),
        ),
    ]
