# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20170622_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Size'),
        ),
    ]
