# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20170623_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
