# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20170623_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='est_delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
