# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_product_range_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='range_type',
        ),
        migrations.AddField(
            model_name='collection',
            name='range_type',
            field=models.CharField(choices=[('LUX', 'Luxury'), ('CLA', 'Classic'), ('PRI', 'Price')], default='CLA', max_length=3),
        ),
    ]
