# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_productmodel_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location name')),
            ],
        ),
        migrations.CreateModel(
            name='StockLocationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockLocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Material')),
            ],
        ),
    ]
