# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_remove_material_quantity_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',)},
        ),
    ]
