# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20170624_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='production_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.StockLocation'),
            preserve_default=False,
        ),
    ]
