# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_collection_production_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterial',
            options={'ordering': ('material', 'product')},
        ),
    ]
