# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20170626_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'ordering': ('name',)},
        ),
    ]
