# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_auto_20170626_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit_usage',
            field=models.CharField(choices=[('HU', 'Hours'), ('PI', 'Pieces'), ('ME', 'Meters'), ('KG', 'Kilograms')], max_length=2, verbose_name='Usage unit'),
        ),
    ]
