# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20170626_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpattern',
            name='surface_area',
            field=models.FloatField(default=0, verbose_name='Surface Area in cm2'),
        ),
    ]
