# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_auto_20170706_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelproductiondescription',
            name='product_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductModel'),
            preserve_default=False,
        ),
    ]
