# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_productmodelproductiondescription_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeBreeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_breed', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='size',
            name='measurements',
            field=models.TextField(default=1, verbose_name='Describe target group measurements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizebreeds',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Size'),
        ),
    ]
