# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20170706_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeBreeds',
            new_name='SizeBreed',
        ),
    ]
