# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_productmodel_original_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbrellaProductBillOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Material')),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='UmbrellaProduct',
        ),
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='UmbrellaProductImage',
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='product',
        ),
        migrations.RenameField(
            model_name='umbrellaproductimage',
            old_name='product',
            new_name='umbrella_product',
        ),
        migrations.DeleteModel(
            name='BillOfMaterial',
        ),
        migrations.AddField(
            model_name='umbrellaproductbillofmaterial',
            name='umbrella_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.UmbrellaProduct'),
        ),
    ]
