# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_auto_20170711_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='product_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='productbillofmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
    ]
