# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_auto_20170711_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='umbrella_product_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.UmbrellaProductModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umbrellaproduct',
            name='umbrella_product_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.UmbrellaProductModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umbrellaproductmodelimage',
            name='umbrella_product_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.UmbrellaProductModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umbrellaproductmodelproductiondescription',
            name='umbrella_product_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.UmbrellaProductModel'),
            preserve_default=False,
        ),
    ]
