# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_auto_20170711_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbillofmaterial',
            name='quantity_needed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
