# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_auto_20170711_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='umbrellaproductmodel',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
