# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_auto_20170715_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocationOnItsWayMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Material')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockLocation')),
            ],
        ),
        migrations.AddField(
            model_name='stocklocationitem',
            name='quantity_on_its_way',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
