# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_auto_20170720_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocationitem',
            name='quantity_in_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocklocationitem',
            name='quantity_on_its_way',
            field=models.FloatField(default=0.0),
        ),
    ]
