# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_auto_20170723_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='size_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
