# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_auto_20170726_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellaproduct',
            name='_original_umbrella_product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OriginalUmbrellaProductModel', to='inventory.UmbrellaProductModel'),
        ),
    ]
