# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_remove_umbrellaproduct__original_umbrella_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelpattern',
            name='pattern_image',
            field=models.FileField(upload_to='media/product_model/patterns/image/%Y/%m/%d', verbose_name='Pattern PDF-file'),
        ),
        migrations.AlterField(
            model_name='productmodelpattern',
            name='pattern_vector',
            field=models.FileField(upload_to='media/product_model/patterns/vector/%Y/%m/%d', verbose_name='Pattern DXF-file'),
        ),
    ]
