# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_auto_20170727_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sku', 'product_model')},
        ),
    ]
