# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_auto_20170728_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('umbrella_product_model', 'size')},
        ),
    ]
