# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_auto_20170728_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='size_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Internal size description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size_description',
            field=models.TextField(blank=True, null=True, verbose_name='Commercial size description'),
        ),
    ]
