# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_stocklocationitem_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialimage',
            name='name',
        ),
    ]
