# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_remove_materialimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='fabric_width',
            field=models.CharField(default=0, max_length=3, verbose_name='Fabric width in cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='roll_width',
            field=models.CharField(default=0, max_length=3, verbose_name='Roll width in cm'),
            preserve_default=False,
        ),
    ]
