# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_auto_20170906_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fabric_width',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Fabric width in cm'),
        ),
        migrations.AlterField(
            model_name='material',
            name='roll_width',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Roll width in cm'),
        ),
    ]
