# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 20:50
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('inventory', '0071_auto_20170906_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
