# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_auto_20170912_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialimage',
            name='image',
            field=models.ImageField(upload_to='media/materials/images/%Y/%m/%d'),
        ),
    ]
