# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_auto_20170917_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umbrellaproductmodel',
            old_name='umbrella_product_model',
            new_name='production_remark',
        ),
    ]
