# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_productmodelpattern_times_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelpattern',
            name='pattern_type',
            field=models.CharField(default='FA', max_length=2),
        ),
    ]
