# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_productmodelpattern_pattern_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelpattern',
            name='pattern_type',
            field=models.CharField(choices=[('FA', 'Fabric'), ('FO', 'Foam'), ('FI', 'Hollow Fibres')], default='FA', max_length=2),
        ),
    ]
