# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0086_auto_20170917_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelpattern',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodelpattern',
            name='times_to_use',
            field=models.IntegerField(default=1),
        ),
    ]
