# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0087_auto_20170917_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionNotesUmbrellaProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('image', models.ImageField(upload_to='media/production/notes/images/%Y/%m/%d')),
                ('umbrella_product', models.ManyToManyField(to='inventory.UmbrellaProduct')),
            ],
        ),
    ]
