# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0088_productionnotesumbrellaproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionNotesUmbrellaProducts',
            new_name='ProductionNotesUmbrellaProduct',
        ),
    ]
