# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0089_auto_20170918_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionNotesUmbrellaProduct',
            new_name='UmbrellaProductProductionNote',
        ),
    ]
