# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_auto_20170918_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UmbrellaProductProductionNote',
            new_name='UmbrellaProductModelProductionNote',
        ),
        migrations.RemoveField(
            model_name='umbrellaproductmodelproductionnote',
            name='umbrella_product',
        ),
        migrations.AddField(
            model_name='umbrellaproductmodelproductionnote',
            name='umbrella_product_model',
            field=models.ManyToManyField(to='inventory.UmbrellaProductModel'),
        ),
    ]
