# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_auto_20170918_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellaproductmodelproductionnote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/production/notes/images/%Y/%m/%d'),
        ),
    ]
