# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0092_auto_20170918_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellaproductmodelproductionnote',
            name='umbrella_product',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.UmbrellaProduct'),
        ),
        migrations.AlterField(
            model_name='umbrellaproductmodelproductionnote',
            name='umbrella_product_model',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.UmbrellaProductModel'),
        ),
    ]
