# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_auto_20170919_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellaproductmodelproductionnote',
            name='umbrella_product',
            field=models.ManyToManyField(blank=True, to='inventory.UmbrellaProduct'),
        ),
        migrations.AlterField(
            model_name='umbrellaproductmodelproductionnote',
            name='umbrella_product_model',
            field=models.ManyToManyField(blank=True, to='inventory.UmbrellaProductModel'),
        ),
    ]
