# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0094_auto_20170920_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umbrellaproductmodelproductionnote',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='umbrellaproductmodelproductionnote',
            old_name='note',
            new_name='note_en',
        ),
    ]
