# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0095_auto_20170921_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellaproductmodelproductionnote',
            name='name_cz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='umbrellaproductmodelproductionnote',
            name='note_cz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
