# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0097_auto_20170921_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umbrellaproductmodel',
            old_name='production_remark',
            new_name='production_remark_en',
        ),
        migrations.AddField(
            model_name='umbrellaproduct',
            name='production_remark_cz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
