# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_auto_20170921_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellaproductmodel',
            name='production_remark_cz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
