# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0099_umbrellaproductmodel_production_remark_cz'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='name_cz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
