# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_umbrellaproductmodelproductionissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_created_in_sprintpack',
            field=models.BooleanField(default=False),
        ),
    ]
