# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_product__created_in_sprintpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellaproductmodel',
            name='customs_code_export',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
