# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0104_umbrellaproduct_hs_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umbrellaproduct',
            old_name='hs_code',
            new_name='export_hs_code',
        ),
    ]
