# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0105_auto_20171013_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellaproduct',
            name='export_composition_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
