# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0106_umbrellaproduct_export_composition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umbrellaproduct',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='next_available',
            field=models.DateField(blank=True, null=True),
        ),
    ]
