# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_auto_20171106_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='brand',
            field=models.CharField(choices=[('SUZYS', "Suzy's"), ('SY', 'S&Y'), ('PRIV', 'Private Label')], default='SUZYS', max_length=5),
        ),
    ]
