# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0109_auto_20171201_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='range_type',
            field=models.CharField(choices=[('LUX', 'Luxury'), ('CLA', 'Classic'), ('PRI', 'Price'), ('PRV', 'Private')], default='CLA', max_length=3),
        ),
    ]
