# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0112_material_sample_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='sample_box_number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
