# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
        ('inventory', '0113_auto_20171203_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellaproduct',
            name='custom_label_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logos.LabelLogo'),
        ),
    ]
