# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0116_auto_20180115_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='measurements',
            field=models.TextField(blank=True, null=True, verbose_name='Describe target group measurements'),
        ),
    ]
