# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-19 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0118_auto_20180217_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellaproduct',
            name='accounting_code',
            field=models.CharField(choices=[('212', "Suzy's range"), ('211', "Suzy's custom range"), ('214', 'Beach Products')], default='212', max_length=20),
        ),
    ]
