# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0120_umbrellaproductimage_is_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellaproductimage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
