# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0006_auto_20170720_1707'),
        ('inventory', '0064_auto_20170727_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('SH', 'Shipped'), ('FI', 'Arrived')], default='DR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='contacts.OwnAddress')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='contacts.OwnAddress')),
            ],
        ),
        migrations.CreateModel(
            name='InternalTransportMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('internal_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.InternalTransport')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Material')),
            ],
        ),
    ]
