# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20170728_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltransport',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
