# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_internaltransport_shipping_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internaltransportmaterial',
            options={'ordering': ('material',)},
        ),
    ]
