# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20170910_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaltransport',
            name='status',
        ),
        migrations.AddField(
            model_name='internaltransport',
            name='_has_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaltransport',
            name='_is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaltransport',
            name='_ready_for_shipment',
            field=models.BooleanField(default=False),
        ),
    ]
