# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_auto_20170728_1501'),
        ('sales', '0002_auto_20170729_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('AC', 'Active'), ('OB', 'Obselete')], default='DR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrp', models.FloatField()),
                ('per_6', models.FloatField()),
                ('per_12', models.FloatField()),
                ('per_48', models.FloatField()),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.PriceList')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('WC', 'Waiting for client approval'), ('WA', 'Waiting for approval'), ('PM', 'Pending Materials'), ('PR', 'In Production'), ('PS', 'Pending Shipping'), ('SH', 'Shipped')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='salesorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.PriceListItem'),
        ),
    ]
