# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170729_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='per_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='per_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='per_48',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='per_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='rrp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
