# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20170729_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
