# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorder_discount_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='invoice_to',
        ),
    ]
