# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_salesorder_invoice_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderproduct',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
