# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesorder__xero_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='_xero_invoice_number',
            new_name='_xero_invoice_id',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
