# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20170911_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
