# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesorder_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='client_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
