# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_salesorder_client_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
