# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesorder_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='client_reference',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
