# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20171001_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ('created_at',)},
        ),
    ]
