# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20171011_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesOrder')),
            ],
        ),
    ]
