# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesorder_partial_delivery_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='transport_cost',
            field=models.FloatField(default=0),
        ),
    ]
