# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_salesorder_transport_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ('-created_at',)},
        ),
    ]
