# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20171024_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('WC', 'Waiting for client approval'), ('WA', 'Waiting for approval'), ('PM', 'Pending Materials'), ('PR', 'In Production'), ('PS', 'Pending Shipping'), ('PD', 'Partially Shipped'), ('SH', 'Shipped')], default='DR', max_length=2),
        ),
    ]
