# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_merge_20171011_2212'),
        ('sales', '0023_auto_20171031_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField()),
                ('sales_report', models.FileField(blank=True, null=True, upload_to='media/sales/sales_reports/%Y/%m/%d')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionNoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.CommissionNote')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.SalesOrder', unique=True)),
            ],
        ),
    ]
