# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_commissionnote_commissionnoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionnoteitem',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sales.SalesOrder'),
        ),
    ]
