# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_auto_20171103_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionnote',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
    ]
