# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_commissionnote_commission_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
