# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_pricelistitem_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderproduct',
            old_name='product',
            new_name='price_list_item',
        ),
    ]
