# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20171105_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistitem',
            name='active',
        ),
    ]
