# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_agent_active'),
        ('sales', '0031_remove_pricelistitem_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListAutoSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('email_to', models.CharField(blank=True, max_length=100, null=True)),
                ('email_to_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Agent')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Relation')),
            ],
        ),
    ]
