# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_auto_20171106_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistautosend',
            name='format',
            field=models.CharField(choices=[('csv', 'csv'), ('pdf', 'pdf'), ('json', 'json')], default='pdf', max_length=4),
        ),
    ]
