# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_pricelistautosend_format'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceListAutoSend',
            new_name='PriceListSetting',
        ),
    ]
