# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_auto_20171127_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together=set([('country', 'currency', 'customer_type')]),
        ),
    ]
