# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_salesorder_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetransport',
            name='price_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.PriceList'),
            preserve_default=False,
        ),
    ]
