# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_pricelist_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderdelivery',
            name='status',
            field=models.CharField(choices=[('AUTO', 'Automatic Shipment'), ('MANU', 'Manual Change')], default='AUTO', max_length=4),
        ),
    ]
