# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0032_auto_20171127_1230'),
        ('sales', '0045_salesorderdelivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Relation', verbose_name='Client if priclist is for private label products'),
        ),
    ]
