# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_pricelist_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='client',
        ),
    ]
