# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-06 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_remove_pricelist_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceListSetting',
            new_name='PriceListAssignment',
        ),
    ]
