# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_auto_20171206_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='reference',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
