# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_pricelist_reference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceList',
            new_name='OldPriceList',
        ),
        migrations.RenameModel(
            old_name='PriceListItem',
            new_name='OldPriceListItem',
        ),
        migrations.RenameModel(
            old_name='PriceTransport',
            new_name='OldPriceTransport',
        ),
        migrations.AlterField(
            model_name='pricelistassignment',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricelists.PriceList'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricelists.PriceList'),
        ),
        migrations.AlterField(
            model_name='salesorderproduct',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricelists.PriceListItem'),
        ),
    ]
