# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_auto_20171209_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='sample_order',
            field=models.BooleanField(default=False),
        ),
    ]
