# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_salesorder_sample_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('WC', 'Waiting for client approval'), ('WA', 'Waiting for approval'), ('PM', 'Pending Materials'), ('PR', 'In Production'), ('PS', 'Pending Shipping'), ('PD', 'Partially Shipped'), ('SH', 'Shipped'), ('CA', 'Cancelled'), ('RF', 'Refunded')], default='DR', max_length=2),
        ),
    ]
